Infrastructure:
- changed-files:
  - any-glob-to-any-file:
    - .github/**/*
    - .pre-commit-config.yaml
    - .readthedocs.yml
    - .gitignore
    - pyproject.toml
    - setup.cfg

GitHub:
- changed-files:
  - any-glob-to-any-file:
    - .github/**/*

Docs:
- changed-files:
  - any-glob-to-any-file:
    - docs/**/*
