name: "Pull Request Labeler"

on:
  issues:
    types:
    - opened
  pull_request_target:
    types:
    - opened

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5 # Uploads repository content to the runner
      with:
        repository: "cosmology-api/cosmology.api"
    - uses: actions/labeler@v6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
