name: Build and Publish

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_wheel_building:
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      upload_to_pypi: false
      upload_to_anaconda: false
      test_extras: test
      test_command: pytest -p no:warnings
      targets: |
        - cp39-manylinux_x86_64

  build_and_publish:
    needs: test_wheel_building
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      upload_to_pypi: true
      upload_to_anaconda: true
      anaconda_user: cosmology
      anaconda_package: cosmology.api

      test_extras: test
      test_command: pytest -p no:warnings
      targets: |
        # Linux wheels

        - cp39-manylinux_x86_64
        - cp310-manylinux_x86_64
        - cp311-manylinux_x86_64

        # MacOS X wheels

        - cp39*macosx_x86_64
        - cp310*macosx_x86_64
        - cp311*macosx_x86_64

        - cp39*macosx_arm64
        - cp310*macosx_arm64
        - cp311*macosx_arm64

        # Windows wheels

        - cp39*win32
        - cp310*win32
        - cp311*win32

        - cp39*win_amd64
        - cp310*win_amd64
        - cp311*win_amd64

    secrets:
      pypi_token: ${{ secrets.pypi_token }}
      anaconda_token: ${{ secrets.anaconda_token }}
