name: Build and Publish

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_wheel_building:
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: false
      upload_to_anaconda: false
      test_extras: test
      test_command: pytest -p no:warnings

  build_and_publish:
    needs: test_wheel_building
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: refs/tags/v
      upload_to_anaconda: true
      anaconda_user: cosmology
      anaconda_package: cosmology.api

      test_extras: test
      test_command: pytest -p no:warnings

    secrets:
      pypi_token: ${{ secrets.pypi_token }}
      anaconda_token: ${{ secrets.anaconda_token }}
